export const WeatherCodeToDescription = (code) => {
  const map = {
    0: "Clear",
    1: "Mainly clear",
    2: "Partly cloudy",
    3: "Cloudy",
    45: "Fog",
    48: "Depositing rime" ,
    51: "Drizzle light",
    53: "Drizzle moderate",
    55: "Drizzle dense",
    56: "Freezing drizzle",
    57: "Freezing drizzle",
    61: "Rain slight",
    63: "Rain moderate",
    65: "Rain heavy",
    66: "Freezing rain",
    67: "Freezing rain",
    71: "Snow slight",
    73: "Snow moderate",
    75: "Snow heavy",
    77: "Snow grains",
    80: "Rain showers",
    81: "Rain showers",
    82: "Rain showers",
    85: "Snow showers",
    86: "Snow showers",
    95: "Thunderstorm",
    96: "Thunderstorm",
    99: "Thunderstorm",
  };
  return map[code] || "Unknown";
};
